### ISSUE TITLE
Needs to improve tests

### ISSUE THREAD

**Issue by gsilvapt** [ubuconeurope/present-switch#1]
Tests are not covering full functionality and to ensure most functionalities are testable, it may be needed to do some refactoring.

It would be great if we ensured that:

- We can have a template HTML file somewhere living in `testdata/` and we can update its contents accordingly;
- Ensure the HTTP server runs and we can connect with a client;

**Comment by gsilvapt** [comment]
@tcarreira With all tests you added, do you think there is any area that could be improved?

**Comment by tcarreira** [comment]
There is always a way to improve, but I think there is no need for a specific issue 👍

**Comment by gsilvapt** [comment]
Thanks. That was my point.
